version: "3.7"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - hass_config:/config  # config
      - hass_localtime:/etc/localtime:ro  # what is localtime? Need to create ahead of time
      - hass_dbus:/run/dbus:ro # dbus Need to create ahead ot time
    restart: always
    privileged: true
    network_mode: host

volumes:
  hass_config:
    driver_opts:
      type: nfs
      device: ":/Docker/Hass/hass_config"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  hass_localtime:
    driver_opts:
      type: nfs
      device: ":/Docker/Hass/hass_localtime"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
  hass_dbus:
    driver_opts:
      type: nfs
      device: ":/Docker/Hass/hass_dbus"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
